import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from './profile.module.css'
import Navbar from '../sidebar';

export default function Profile() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device_width, initial_scale=1" />
        <Link className={styles.a} rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
      </main>
    </>
  )
}
